services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ec3movies
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    networks:
      - app-network
  ec3movies:
    build: .
    ports:
      - "8099:8099"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: 123456
    networks:
      - app-network
networks:
  app-network:
    driver: bridge