services:
  mysql:
    image: mysql:8.0.33
    environment:
      MYSQL_DATABASE: ec3movies
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
  restprueba:
    build: .
    ports:
      - "8099:8099"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: 123456